#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom --vsync &
#polybar example &
~/Config/polybar2/launch.sh
dunst &
~/.fehbg &
xfce4-power-manager &

bspc monitor eDP -d I II III IV V VI VII VIII IX
bspc monitor HDMI-A-0 -d X

bspc config border_width         4
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
