#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom --vsync --backend glx &
#polybar example &
~/Config/polybar2/launch.sh
dunst &
~/.fehbg &
xfce4-power-manager &

bspc monitor eDP -d "1" "2" "3" "4" "5" "6" "7" "8" "9"
bspc monitor HDMI-A-0 -d "10"

bspc config border_width         3
bspc config focused_border_color "#6AD6EB"
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
